/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'customerName' : string,
  'bookingId' : bigint,
  'customerPhone' : string,
  'sareeId' : string,
  'timestamp' : bigint,
}
export interface BookingRequest {
  'customerName' : string,
  'customerPhone' : string,
  'sareeId' : string,
}
export type ExternalBlob = Uint8Array;
export interface SareeListing {
  'id' : string,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'timestamp' : bigint,
  'image' : ExternalBlob,
  'price' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSareeListing' : ActorMethod<
    [string, string, string, bigint, boolean, ExternalBlob],
    undefined
  >,
  'deleteSareeListing' : ActorMethod<[string], undefined>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllSareeListings' : ActorMethod<[], Array<SareeListing>>,
  'getAvailableSareeListings' : ActorMethod<[], Array<SareeListing>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSareeById' : ActorMethod<[string], SareeListing>,
  'getSellerPhoneNumber' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'setSellerPhoneNumber' : ActorMethod<[string], undefined>,
  'submitBooking' : ActorMethod<[BookingRequest], bigint>,
  'updateSareeListing' : ActorMethod<
    [string, string, string, bigint, boolean, ExternalBlob],
    undefined
  >,
  'uploadFile' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];