/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Booking = IDL.Record({
  'customerName' : IDL.Text,
  'bookingId' : IDL.Nat,
  'customerPhone' : IDL.Text,
  'sareeId' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SareeListing = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'timestamp' : IDL.Int,
  'image' : ExternalBlob,
  'price' : IDL.Nat,
});
export const BookingRequest = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'sareeId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSareeListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, ExternalBlob],
      [],
      [],
    ),
  'deleteSareeListing' : IDL.Func([IDL.Text], [], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllSareeListings' : IDL.Func([], [IDL.Vec(SareeListing)], ['query']),
  'getAvailableSareeListings' : IDL.Func(
      [],
      [IDL.Vec(SareeListing)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSareeById' : IDL.Func([IDL.Text], [SareeListing], ['query']),
  'getSellerPhoneNumber' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'setSellerPhoneNumber' : IDL.Func([IDL.Text], [], []),
  'submitBooking' : IDL.Func([BookingRequest], [IDL.Nat], []),
  'updateSareeListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, ExternalBlob],
      [],
      [],
    ),
  'uploadFile' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Booking = IDL.Record({
    'customerName' : IDL.Text,
    'bookingId' : IDL.Nat,
    'customerPhone' : IDL.Text,
    'sareeId' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SareeListing = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'timestamp' : IDL.Int,
    'image' : ExternalBlob,
    'price' : IDL.Nat,
  });
  const BookingRequest = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'sareeId' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSareeListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, ExternalBlob],
        [],
        [],
      ),
    'deleteSareeListing' : IDL.Func([IDL.Text], [], []),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllSareeListings' : IDL.Func([], [IDL.Vec(SareeListing)], ['query']),
    'getAvailableSareeListings' : IDL.Func(
        [],
        [IDL.Vec(SareeListing)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSareeById' : IDL.Func([IDL.Text], [SareeListing], ['query']),
    'getSellerPhoneNumber' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'setSellerPhoneNumber' : IDL.Func([IDL.Text], [], []),
    'submitBooking' : IDL.Func([BookingRequest], [IDL.Nat], []),
    'updateSareeListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, ExternalBlob],
        [],
        [],
      ),
    'uploadFile' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };